version: "3.8"

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      TZ: "Asian/Shanghai"
      MYSQL_ROOT_PASSWORD: qwerty
    volumes:
      - ./data/mysql:/var/lib/mysql
