// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	ArchivedBundle  *archivedBundle
	ArchivedFile    *archivedFile
	MirroredGitRepo *mirroredGitRepo
	PhotoFile       *photoFile
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ArchivedBundle = &Q.ArchivedBundle
	ArchivedFile = &Q.ArchivedFile
	MirroredGitRepo = &Q.MirroredGitRepo
	PhotoFile = &Q.PhotoFile
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		ArchivedBundle:  newArchivedBundle(db, opts...),
		ArchivedFile:    newArchivedFile(db, opts...),
		MirroredGitRepo: newMirroredGitRepo(db, opts...),
		PhotoFile:       newPhotoFile(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ArchivedBundle  archivedBundle
	ArchivedFile    archivedFile
	MirroredGitRepo mirroredGitRepo
	PhotoFile       photoFile
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ArchivedBundle:  q.ArchivedBundle.clone(db),
		ArchivedFile:    q.ArchivedFile.clone(db),
		MirroredGitRepo: q.MirroredGitRepo.clone(db),
		PhotoFile:       q.PhotoFile.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		ArchivedBundle:  q.ArchivedBundle.replaceDB(db),
		ArchivedFile:    q.ArchivedFile.replaceDB(db),
		MirroredGitRepo: q.MirroredGitRepo.replaceDB(db),
		PhotoFile:       q.PhotoFile.replaceDB(db),
	}
}

type queryCtx struct {
	ArchivedBundle  *archivedBundleDo
	ArchivedFile    *archivedFileDo
	MirroredGitRepo *mirroredGitRepoDo
	PhotoFile       *photoFileDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ArchivedBundle:  q.ArchivedBundle.WithContext(ctx),
		ArchivedFile:    q.ArchivedFile.WithContext(ctx),
		MirroredGitRepo: q.MirroredGitRepo.WithContext(ctx),
		PhotoFile:       q.PhotoFile.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
